### ISSUE TITLE
Fail to run on Win10 x64

### ISSUE THREAD

**Issue by liorbp** [evil-e/sdb-explorer#1]
Compile sdb-explorer with VS2013 on Windows 7 x64 and it worked just fine.
After migrating to Win10, when analyzing SDB, the tree structure is extracted OK, but all content is missing.
[http://imgur.com/aUOIEcD](url)

**Comment by evil-e** [comment]
Thanks for reporting this issue.  I will try to replicate the issue and fix.

Is their a specific SDB file you were trying to parse?

**Comment by evil-e** [comment]
@liorbp Please test the fix in commit: https://github.com/evil-e/sdb-explorer/commit/1d2bc136332a08cfc1fce9e142f9e95270f9d364

**Comment by liorbp** [comment]
Fixed! :+1: 
Thank you
